apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-product-catalogue
  labels:
    app: product-catalogue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        command: {{ .Values.command }}
        volumeMounts:
        - name: app-config
          mountPath: /app/config
      volumes:
      - name: app-config
        configMap:
          name: {{ .Release.Name }}-product-catalogue-configmap
