apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product-catalogue-service
  labels:
    app: product-catalogue
spec:
  selector:
    app: product-catalogue
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
