apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-shopfront
  labels:
    app: shopfront
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shopfront
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        command: {{ .Values.command }}
      volumes:
      - name: app-config
        configMap:
          name: {{ .Release.Name }}-shopfront-configmap
