# .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: <your-gcp-project-id>
  IMAGE_NAME: <your-image-name>
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate to GCP using Service Account
      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Deploy to Kubernetes cluster on GCP using HELM
      - name: Deploy to Kubernetes
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |
          helm upgrade --install ${{ env.IMAGE_NAME }} ./helm \
            --set image.repository=${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.IMAGE_TAG }}
